FROM mcr.microsoft.com/dotnet/runtime:7.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["src/workers/BalanceWorkerService/BalanceWorkerService.csproj", "BalanceWorkerService/"]
RUN dotnet restore "src/workers/BalanceWorkerService/BalanceWorkerService.csproj"
COPY . .
WORKDIR "/src/BalanceWorkerService"
RUN dotnet build "BalanceWorkerService.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "BalanceWorkerService.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "BalanceWorkerService.dll"]
